# Generated by Django 3.1.7 on 2021-04-03 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(121)])),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('zipcode', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
