# Generated by Django 3.2.6 on 2021-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20210407_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_related_name': 'User-Person'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(default='admin-slug', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('house', 'street', 'city', 'state', 'country', 'zipcode')},
        ),
    ]
